services:
  iobroker-history-api:
    container_name: iobroker-history-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IO_BROKER_HOST
      - IO_BROKER_INSTANCE
    ports:
      - "80:80"
